#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'

alias c='clear'

#PS1='[\u@\h \W]\$ '

PS1='[\[\033[1;36m\]\u\[\033[1;36m\]@\[\033[1;36m\]\h\[\033[0;37m\]\w]\[\033[0;37m\]\[\033[0m\] '

LS_COLORS=$LS_COLORS:'di=34:' ; export LS_COLORS
LS_COLORS+=':ow=34'

export TERM=vt100

neofetch
